# _config.yml
title:       Ustin M. Vaskin Articles Blog
email:       ustin.vaskin2011@gmail.com
author:      Ustin M. Vaskin
description: >-
 GitHub Pages blog.

# For project pages:
baseurl:     "/articles"                       # the sub-path your site lives at
url:         "https://ustinvaskin.github.io"   # NO angle brackets!

theme:       minima
plugins:
  - jekyll-feed
