title:         My Articles Blog
email:         ustin.vaskin2011@gmail.com
author:        Ustin M. Vaskin
description: >-
  A simple, easy-to-update GitHub Pages blog.
baseurl:       ""       # leave empty for user site
url:           "https://<ustinvaskin>.github.io"

theme:         minima
plugins:
  - jekyll-feed
